### ISSUE TITLE
Suggestion: Change some of the command names

### ISSUE THREAD

**Issue by blindman2k** [matt-haines/imp-cli#6]
1. imp init: It's a bit unclear what this is going to do from the description. Is "imp create" a better command?
2. imp deploy: Give we have "imp pull" wouldn't "imp push" be a better choice? Also, "deploy" is the word used for deploying new code to blessed imps.

**Comment by cat-haines** [comment]
1. `imp init` does a similar thing to `git init` and `npm init` - it initializes the current directory to a new imp-cli project. Depending on the desired setup, you may or may not be "creating" models, bonds, etc. I'd like to leave this one as is.
2. I like the suggestion for `imp push` - especially since there's a good chance the Build API may be able to actually "deploy" code (in a production sense) at some point in the future.
